### ISSUE TITLE
Hey!

### ISSUE THREAD

**Issue by TrickJoker312** [cristomald/Unblocked-games-cristomald#1]
Hey! I noticed you were using some links from my repository. I would appreciate it if you could credit me, for using the sites on your repository. Have a nice day!
(I have a license. xD)

**Comment by cristomald** [comment]
Okay

**Comment by cristomald** [comment]
i have left credits to the on i used of yours if you find any more links that ar from you reply here

**Comment by TrickJoker312** [comment]
Okay, thanks!
